import StartingPageContent from "@/components/starting-page/starting-page";
import Head from "next/head";

export default function HomePage() {
  return (
    <>
      <Head>
        <title>Next JS Authentication</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <StartingPageContent />
      </main>
    </>
  );
}
